# Generated by Django 2.2.5 on 2019-11-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentkieruneksemestr',
            old_name='nr_albumu',
            new_name='id_studenta',
        ),
    ]
